### ISSUE TITLE
Can't load libQt5Core.so.5 on Ubuntu

### ISSUE THREAD

**Issue by Malina09** [ostis-ai/ostis-web-platform#42]
**Describe the bug**
Problem with libQt5Core.so.5 for kbe

**To Reproduce**
Get last release from github, try to launch KBE and make a scg

**Expected behavior**
Normal work

**Screenshots**
![image](https://user-images.githubusercontent.com/63506873/214290515-b93da5de-341b-4a00-ad67-26d7f4708711.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - Version KBE: 0.4.1

**Additional context**
Some people report this problem

**Comment by Malina09** [comment]
In version 0.4.1 there is no backward compatibility with Qt versions, does not work with version Qt 5.15.3.
Solution to the problem: put a separate version. Qt 5.12.8 and replaced the path in the ./kbe.sh.
![image](https://user-images.githubusercontent.com/63506873/220303044-98ecf8d3-a99a-490b-a93f-444c59a7e8cb.png)

**Comment by SHtress** [comment]
Try to check current pre-release, we updated it recently. Also we have separate repository for KBE, please move this issue to it.
